name: Hello Word Workflow

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Word
        run: echo "Hello Word!"

      - name: Print date
        run: date

      - name: List directory contents
        run: ls -l